pacificclimate/design-value-explorer

dve/app.py
dve/layout.py
dve/utils.py

This PR further cleans up the code, breaking the layout into smaller component parts and using the Dash Bootstrap Components consistently and correctly. The DBC cleanup includes some improvements to layout as well. Finally, some of the controls have been improved, either by using a more appropriate one or by using the same one better. In addition to improving usability and readability, it has also simplified the code.

More cleanup

---

README.md
docker/dev-local/docker-compose.yml
dve/app.py
dve/colorbar.py
dve/layout.py

Resolves #34 
Also cleans up code a little, and improves Docker dev-local.

Simplify colourbar ticks

---

config.yml
docker/dev-local/config.yml
dve/app.py
dve/layout.py

Add DV descriptions

---

dve/app.py
dve/layout.py

At hover display with lat, lon, DV

---

docker/dev-local/config.yml
docker/dev-local/docker-compose.yml
dve/app.py
dve/download_utils.py
dve/layout.py
dve/map_utils.py

Add data download

---

dve/app.py
dve/layout.py

Remove Raster switch

---

dve/app.py
dve/layout.py

Fix layout for narrower windows

---

config.yml
docker/dev-local/config.yml

Add descriptions and units to config

---

.gitignore
README.md
config.yml
docker/dev-local/config.yml
dve/app.py
dve/layout.py

Resolves #50 
Config now contains values for disabling logarithmic scale and setting default scale.

Set scale control according to DV

---

README.md
config.yml
docker/dev-local/config.yml
docker/dev-local/entrypoint.sh
dve/app.py
dve/data.py

Set palette according to DV. Update config with preferred palettes.

Improve colour palette selection

---

docker/dev-local/config.yml
docker/dev-local/docker-compose.yml
dve/app.py
dve/layout.py

Resolves #14 
Also adds simple, out of box column filtering to table C2.

Add NBCC 2015 values to table C2

---

.github/workflows/anchore-analysis.yml
requirements.txt

Fixes (partially) #74 
Specifically:
- Fixes Docker build of image for scan
- Fixes one of the vulnerabilities
- Assigns two others as unfixable
- Leaves one vulnerability unfixed for now

Partial fix for security vulnerabilities

---

config.yml
docker/dev-local/config.yml
dve/app.py
dve/callbacks/map_pointer.py
dve/config.py
dve/download_utils.py
dve/layout.py

Validate config

---

config.yml
docker/dev-local/config.yml

Add several missing CFs

---

config.yml

Update prod config with missing dvs

---

dve/callbacks/map_figure.py

Add climate regime to map label

---

config.yml
docker/dev-local/config.yml
dve/callbacks/table_c2.py
dve/layout.py

Indicate that station data is historical only

---

config.yml
docker/dev-local/config.yml
dve/layout.py

Always show modebar (configurable)

---

config.yml
docker/dev-local/config.yml
dve/callbacks/map_figure.py
dve/layout.py

Resolves #103 
And places a lot of control configuration in config.

Add control to turn on/off grid lines

---

config.yml
docker/dev-local/config.yml

Reduce grid density (config)

---

dve/data.py

Resolves #118 
Applies a fairly draconian solution. Issue in for greater concurrency: #121

Access files under cache thread lock

---

docker/dev-local/config.yml
dve/callbacks/map_pointer.py
dve/config.py
dve/download_utils.py

Fix units in download files

---

dve/callbacks/map_pointer.py
dve/download_utils.py

Download only reconstruction values

---

config.yml
docker/dev-local/config.yml

Update Table C2 labels

---

config.yml
docker/dev-local/config.yml
dve/callbacks/map_figure.py
dve/config.py
dve/layout.py

I141 map title

---

dve/callbacks/map_figure.py

Fix map hover popup text

---

config.yml
docker/dev-local/config.yml
docker/dev-local/docker-compose.yml
dve/callbacks/map_figure.py
dve/colorbar.py
dve/data.py
dve/layout.py

Improve log scale colourbar

---

dve/callbacks/map_figure.py
dve/generate_iso_lines.py
dve/layout.py
dve/math_utils.py

This PR eliminates map updates due to viewport changes (zoom, pan) when:
- grid is not shown
- zoom level does not change (i.e., pan only)

Improve behaviour with lat-lon grid

---

dve/callbacks/map_figure.py
dve/callbacks/table_c2.py
dve/layout.py

Don't bother updating tab content that's invisible. Seems to make the app a bit more responsive.

Update only selected tab

---

README.md
docker/dev-local/Dockerfile
docker/dev-local/docker-compose.yml
docker/dev-local/entrypoint.sh

This PR adds and uses a non-privileged user to execute the app in a Docker container.

Improve Docker security

---

dve/layout.py

Improve table loading spinners

---

dve/callbacks/map_pointer.py

Don't update download table when DV changes

---

dve/callbacks/map_figure.py

Round colorbar annotations according to roundto per DV in config. 
Re. #139 , but not a full fix. In some cases (e.g., RL50), the precision is insufficient to distinguish the different ticks (particularly in the lower end of a logarithmic scale).

Round colorbar annotations

---

dve/callbacks/colour_scale.py
dve/callbacks/map_pointer.py
dve/data.py
dve/download_utils.py
dve/generate_iso_lines.py

Apply Black

---

dve/callbacks/map_figure.py
dve/data.py
dve/timing.py
stats.py

Add a context manager for timing blocks of code, and apply it to various data operations.
Also don't create the stations figure unless stations are shown. (it takes 120 ms!)

Add timing

---

dve/callbacks/colour_scale.py
dve/callbacks/map_figure.py
dve/callbacks/map_pointer.py
dve/callbacks/overlay.py
dve/callbacks/table_c2.py
dve/config.py
dve/data.py
dve/download_utils.py
dve/layout.py

Rename things so that they mean what they name, and are consistent with each other.

Consistent naming

---

dve/callbacks/table_c2.py

Resolves #133 
Best done with a cache so that we do not explicitly create and use precomputed tables. Reduces table load time by a factor of about 3.

Cache Table C2 internally

---

config.yml
docker/dev-local/config.yml
dve/callbacks/map_figure.py
dve/generate_iso_lines.py
dve/layout.py
dve/math_utils.py

Extend graticule lat lines to 40 N

---

config.yml
docker/dev-local/config.yml
dve/callbacks/map_figure.py
dve/config.py

Change map title

---

.github/workflows/python-ci.yml
Pipfile
Pipfile.lock
dve/callbacks/map_figure.py
dve/colorbar.py
tests/test_colorbar.py

Resolves #173 
Actual fix was tiny: a missing pair of parentheses.
The rest is establishing tests.

Fix colorscale bugfix

---

README.md
config.yml
docker/dev-local/config.yml
dve/callbacks/colour_scale.py
dve/callbacks/map_figure.py
dve/callbacks/table_c2.py
dve/config.py
tests/test_config.py

Refactors config file according to suggestion in #93 (but does not change colour scales between historical and future).

Refactor config file

---

config.yml
docker/dev-local/config.yml
dve/callbacks/colour_scale.py
dve/config.py

Fix a mistake in refactoring the config

Fix config for scale

---

config.yml
docker/dev-local/config.yml
dve/app.py
dve/callbacks/colour_scale.py
dve/callbacks/local_config.py
dve/callbacks/map_figure.py
dve/callbacks/utils.py
dve/config.py
dve/dict_utils.py
dve/layout.py
tests/test_config.py
tests/test_dict_utils.py

Establish a per-client persistent configuration stored in browser local storage

---

config.yml
docker/dev-local/config.yml

Update a couple of dv configs

---

config.yml
docker/dev-local/config.yml
dve/callbacks/map_figure.py
dve/colorbar.py
dve/layout.py

Put map colorbar in single Graph object

---

docker/dev-local/config.yml
dve/callbacks/local_config.py

- Simpler
- More flexible (now includes distinction between path for global default and local storage)

Refactor local config

---

config.yml
docker/dev-local/config.yml
dve/callbacks/local_config.py
dve/callbacks/overlay.py

Turn off and disable Station ctrl for future datasets

---

config/dvs.yml
dve/config.py

Fix errors occur callbacks for MI, future

---

dve/callbacks/colour_scale.py
dve/callbacks/map_figure.py
dve/callbacks/map_pointer.py
dve/callbacks/table_c2.py
dve/data.py

Fix errors creating map-click download table

---

dve/callbacks/table_c2.py
dve/config.py

Handle unitless DVs

---

config/dvs.yml
config/ui/labels.yml
dve/callbacks/table_c2.py
dve/config.py

Update graph and table titles with Tier info

---

dve/app.py
dve/callbacks/url_query_params.py
dve/layout.py

Set design variable from query parameter
